package com.ejemplos.codesmells.service;

public class ComentarioSmell {

    // HOLAAAAAAAAAAAAAAAAA
    // HOLAAAAAAAAAAAAAAAAA
    // HOLAAAAAAAAAAAAAAAAA
    // HOLAAAAAAAAAAAAAAAAA
    // HOLAAAAAAAAAAAAAAAAA
    // HOLAAAAAAAAAAAAAAAAA
    // HOLAAAAAAAAAAAAAAAAA
    // HOLAAAAAAAAAAAAAAAAA
    // HOLAAAAAAAAAAAAAAAAA
    // HOLAAAAAAAAAAAAAAAAA
    // HOLAAAAAAAAAAAAAAAAA
    // HOLAAAAAAAAAAAAAAAAA
    // HOLAAAAAAAAAAAAAAAAA
    // HOLAAAAAAAAAAAAAAAAA
}
